### ISSUE TITLE
Tilt error in Frank 0.3.2

### ISSUE THREAD

**Issue by ahamid** [trvsdnn/frank#11]
<pre>
[aaron@localhost ~]$ frank new
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': /opt/home/aaron/.gem/ruby/1.8/gems/frank-0.3.2/bin/../lib/frank/tilt.rb:779: syntax error, unexpected tAMPER, expecting '|' (SyntaxError)
        define_method :tag_missing do |tag, attr, &block|
                                                   ^
/opt/home/aaron/.gem/ruby/1.8/gems/frank-0.3.2/bin/../lib/frank/tilt.rb:794: syntax error, unexpected kEND, expecting $end
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /opt/home/aaron/.gem/ruby/1.8/gems/frank-0.3.2/bin/../lib/frank/base.rb:1
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /opt/home/aaron/.gem/ruby/1.8/gems/frank-0.3.2/bin/../lib/frank.rb:15
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /opt/home/aaron/.gem/ruby/1.8/gems/frank-0.3.2/bin/frank:4
    from /opt/home/aaron/.gem/ruby/1.8/bin/frank:19:in `load'
    from /opt/home/aaron/.gem/ruby/1.8/bin/frank:19

[aaron@localhost ~]$ ruby -v
ruby 1.8.6 (2010-02-05 patchlevel 399) [x86_64-linux]
[aaron@localhost ~]$ gem -v
1.3.7
[aaron@localhost ~]$ gem list frank

*** LOCAL GEMS ***

frank (0.3.2)

[aaron@localhost ~]$ uname -a
Linux localhost.localdomain 2.6.33.6-147.fc13.x86_64 #1 SMP Tue Jul 6 22:32:17 UTC 2010 x86_64 x86_64 x86_64 GNU/Linux
[aaron@localhost ~]$ cat /etc/issue.net
Fedora release 13 (Goddard)
Kernel \r on an \m (\l)
</pre>

**Comment by ahamid** [comment]
appears to work on ruby 1.8.7 so I take it that's a prereq
