### ISSUE TITLE
lorem.image argument error

### ISSUE THREAD

**Issue by wyattdanger** [trvsdnn/frank#19]
lorem.image throws an error if only one argument is passed.

This works:
    %img{:src=>lorem.image('450x75', :text => 'Play Video')}

This does not, but should, according to the docs:
    %img{:src=>lorem.image('450x75')}

**Comment by wyattdanger** [comment]
The trace:

```
(__TEMPLATE__):31:in `image'
(__TEMPLATE__):31:in `evaluate_source'
(__TEMPLATE__):27:in `times'
(__TEMPLATE__):27:in `evaluate_source'
/Library/Ruby/Gems/1.8/gems/tilt-0.9/lib/tilt.rb:195:in `evaluate'
/Library/Ruby/Gems/1.8/gems/tilt-0.9/lib/tilt.rb:458:in `evaluate'
/Library/Ruby/Gems/1.8/gems/tilt-0.9/lib/tilt.rb:128:in `render'
/Library/Ruby/Gems/1.8/gems/frank-0.4.0/bin/../lib/frank/base.rb:210:in `tilt'
/Library/Ruby/Gems/1.8/gems/frank-0.4.0/bin/../lib/frank/base.rb:129:in `render'
/Library/Ruby/Gems/1.8/gems/frank-0.4.0/bin/../lib/frank/base.rb:51:in `process'
/Library/Ruby/Gems/1.8/gems/frank-0.4.0/bin/../lib/frank/base.rb:32:in `call!'
/Library/Ruby/Gems/1.8/gems/frank-0.4.0/bin/../lib/frank/base.rb:25:in `call'
/Library/Ruby/Gems/1.8/gems/frank-0.4.0/bin/../lib/frank/middleware/refresh.rb:17:in `call'
/Library/Ruby/Gems/1.8/gems/frank-0.4.0/bin/../lib/frank/middleware/statik.rb:34:in `call'
/Library/Ruby/Gems/1.8/gems/rack-1.2.1/lib/rack/builder.rb:77:in `call'
/Library/Ruby/Gems/1.8/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
/Library/Ruby/Gems/1.8/gems/rack-1.2.1/lib/rack/chunked.rb:15:in `call'
/Library/Ruby/Gems/1.8/gems/rack-1.2.1/lib/rack/handler/mongrel.rb:67:in `process'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:159:in `process_client'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:158:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:158:in `process_client'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:285:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:285:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:285:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:285:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:268:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:268:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:268:in `run'
/Library/Ruby/Gems/1.8/gems/rack-1.2.1/lib/rack/handler/mongrel.rb:38:in `run'
/Library/Ruby/Gems/1.8/gems/frank-0.4.0/bin/../lib/frank/base.rb:302:in `new'
/Library/Ruby/Gems/1.8/gems/frank-0.4.0/bin/frank:123
/usr/bin/frank:19:in `load'
/usr/bin/frank:19
```
