### ISSUE TITLE
no such file to load -- rack/builder

### ISSUE THREAD

**Issue by jerodsanto** [trvsdnn/frank#25]
I get this error when running `frank server` on a just-generated skeleton site. I'm using RVM and Ruby 1.9.2p0.

```
/Users/jerod/.rvm/gems/ruby-1.9.2-p0/gems/frank-1.0.2/lib/frank/base.rb:280:in `new': no such file to load -- rack/builder (LoadError)
from /Users/jerod/.rvm/gems/ruby-1.9.2-p0/gems/frank-1.0.2/lib/frank/cli.rb:117:in `run!'
from /Users/jerod/.rvm/gems/ruby-1.9.2-p0/gems/frank-1.0.2/lib/frank/cli.rb:95:in `run'
from /Users/jerod/.rvm/gems/ruby-1.9.2-p0/gems/frank-1.0.2/bin/frank:20:in `<top (required)>'
from /Users/jerod/.rvm/gems/ruby-1.9.2-p0/bin/frank:19:in `load'
from /Users/jerod/.rvm/gems/ruby-1.9.2-p0/bin/frank:19:in `<main>'
```

Perhaps its a problem with Frank's Gemfile? My system has rack (1.2.1, 1.0.1) installed.

**Comment by trvsdnn** [comment]
I'll try to reproduce this tonight. Hopefully I can get a fix in for 1.0.3

**Comment by trvsdnn** [comment]
I haven't been able to reproduce this. I'm using a fresh install 1.9.2p0 in rvm. Can you show me your gem list?
    $ ruby -v ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-darwin10.5.0]

```
$ gem list

*** LOCAL GEMS ***

daemons (1.0.10)
frank (1.0.2)
gem_plugin (0.2.3)
haml (3.0.24)
mongrel (1.2.0.pre2)
rack (1.2.1)
rake (0.8.7)
tilt (0.9)

$ frank server

-----------------------
 Frank's workin' some magic...
 0.0.0.0:3601 
```

**Comment by jerodsanto** [comment]
Sure.

```
abstract (1.0.0)
actionmailer (3.0.1, 2.3.5)
actionpack (3.0.1, 2.3.5)
activemodel (3.0.1)
activerecord (3.0.1, 2.3.5)
activerecord-intersys-adapter (0.0.1)
activeresource (3.0.1, 2.3.5)
activesupport (3.0.1, 2.3.5)
arel (1.0.1)
autotest (4.4.4)
autotest-fsevent (0.2.3)
autotest-growl (0.2.6)
awesome_print (0.2.1)
builder (2.1.2)
bundler (1.0.3)
capistrano (2.5.19)
classifier (1.3.3)
color-tools (1.3.0)
coloration (0.2.5)
configuration (1.1.0)
crack (0.1.8)
cri (1.0.1)
daemons (1.1.0)
diff-lcs (1.1.2)
directory_watcher (1.3.2)
erubis (2.6.6)
eventmachine (0.12.10)
factory_girl (1.3.2)
factory_girl_rails (1.0)
fast-stemmer (1.0.0)
feed-normalizer (1.5.2)
formtastic (1.1.0)
frank (1.0.2)
ghost (0.2.8)
gmail (0.3.2)
haml (3.0.23, 3.0.22, 3.0.17)
haml-rails (0.3.4)
hashie (0.4.0)
heroku (1.9.13)
highline (1.6.1)
hpricot (0.8.2)
httparty (0.6.1)
httpclient (2.1.5.2)
i18n (0.4.2, 0.4.1)
interactive_editor (0.0.5)
jekyll (0.7.0)
jquery-rails (0.2.4)
json (1.4.6)
json_pure (1.4.6)
launchy (0.3.7)
liquid (2.2.2)
little-plugger (1.1.2)
logging (1.4.3)
loquacious (1.7.0)
mail (2.2.7)
maruku (0.6.0)
mime (0.1)
mime-types (1.16)
multi_json (0.0.4)
mysql (2.8.1)
nanoc (3.1.5)
nanoc3 (3.1.5)
nanotest (0.9.4.1)
net-scp (1.0.4)
net-sftp (2.0.5)
net-ssh (2.0.23)
net-ssh-gateway (1.0.1)
oauth (0.4.4)
plist (3.1.0)
polyglot (0.3.1)
rack (1.2.1)
rack-mount (0.6.13)
rack-test (0.5.6)
rails (3.0.1, 2.3.5)
rails3-generators (0.14.0)
railties (3.0.1)
rake (0.8.7)
rake-builder (0.0.11)
rdiscount (1.6.5)
rdoc (2.5.10)
rest-client (1.4.2)
rspec (2.0.1)
rspec-core (2.0.1)
rspec-expectations (2.0.1)
rspec-mocks (2.0.1)
ruby-gmail (0.2.1)
shared-mime-info (0.1)
shotgun (0.8)
shoulda (2.11.3)
simple-rss (1.2.3)
sinatra (1.0)
smusher (0.4.6)
spoon (0.0.1)
sqlite3-ruby (1.3.1)
syntax (1.0.0)
sys-uname (0.8.4)
textpow19 (0.11.0)
thin (1.2.7)
thor (0.14.3)
tilt (0.9)
treetop (1.4.8)
twitter (0.9.12)
tzinfo (0.3.23)
watchr (0.7)
webby (0.9.4)
wirble (0.1.3)
```

**Comment by manuelmeurer** [comment]
I got the same error as soon as I added a `Gemfile`. Before it worked okay.

```
$ frank server
/Users/manuel/.rvm/gems/ruby-1.9.2-p180@rails3/gems/frank-1.0.8/lib/frank/base.rb:271:in `new': no such file to load -- rack/builder (LoadError)
    from /Users/manuel/.rvm/gems/ruby-1.9.2-p180@rails3/gems/frank-1.0.8/lib/frank/cli.rb:123:in `run!'
    from /Users/manuel/.rvm/gems/ruby-1.9.2-p180@rails3/gems/frank-1.0.8/lib/frank/cli.rb:95:in `run'
    from /Users/manuel/.rvm/gems/ruby-1.9.2-p180@rails3/gems/frank-1.0.8/bin/frank:20:in `<top (required)>'
    from /Users/manuel/.rvm/gems/ruby-1.9.2-p180@rails3/bin/frank:19:in `load'
    from /Users/manuel/.rvm/gems/ruby-1.9.2-p180@rails3/bin/frank:19:in `<main>'
```

My `Gemfile` just contained `gem 'compass'`.

When I added `gem 'frank'`, ran `bundle` again and started the server via `bundle exec frank server`, it works again.

**Comment by Dahie** [comment]
I just ran into the same problem, after updating all gems in my gemset. It resolved by updating the Gemfile.lock by running `bundle update`
