### ISSUE TITLE
View Meta Data Breaking

### ISSUE THREAD

**Issue by bitfyre** [trvsdnn/frank#35]
When I use the following code in my view, based on the README documentation

```
view:
  title: "My Rad Page"
  author: "My Rad Self"
---META

%h1= title
```

I am receiving the following error

```
Something’s Wrong—

The error, « undefined local variable or method `title' for #<Object:0x00000101a4e208> »
occurred in <project>/dynamic/index.haml on line 2.

<project>/dynamic/index.haml:2:in `evaluate_source'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/tilt-0.9/lib/tilt.rb:254:in `instance_eval'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/tilt-0.9/lib/tilt.rb:254:in `evaluate_source'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/tilt-0.9/lib/tilt.rb:195:in `evaluate'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/tilt-0.9/lib/tilt.rb:458:in `evaluate'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/tilt-0.9/lib/tilt.rb:128:in `render'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/frank-1.0.8/lib/frank/base.rb:185:in `tilt'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/frank-1.0.8/lib/frank/base.rb:114:in `render'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/frank-1.0.8/lib/frank/base.rb:40:in `process'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/frank-1.0.8/lib/frank/base.rb:28:in `call!'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/frank-1.0.8/lib/frank/base.rb:21:in `call'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/frank-1.0.8/lib/frank/middleware/refresh.rb:17:in `call'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/frank-1.0.8/lib/frank/middleware/statik.rb:34:in `call'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/rack-1.2.1/lib/rack/builder.rb:77:in `call'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/rack-1.2.1/lib/rack/chunked.rb:15:in `call'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/rack-1.2.1/lib/rack/handler/mongrel.rb:67:in `process'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:165:in `block in process_client'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:164:in `each'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:164:in `process_client'
<path to rvm>/.rvm/gems/ruby-1.9.2-p180@frank/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:291:in `block (2 levels) in run'
```

I am running this with rvm on snow leopard

```
ruby -v
ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-darwin10.6.0]
```

Gems 

```
gem list --local

*** LOCAL GEMS ***

bundler (1.0.0.rc.5)
chunky_png (0.12.0)
compass (0.10.6)
daemons (1.0.10)
frank (1.0.8)
gem_plugin (0.2.3)
haml (3.0.25)
mongrel (1.2.0.pre2)
net-scp (1.0.4)
net-ssh (2.1.0)
rack (1.2.1)
rake (0.8.7)
rdoc (3.5.3)
tilt (0.9)
```

**Comment by trvsdnn** [comment]
The documentation format is a little weird with that example. Your META data shouldn't start with the view key. The example tries to breakdown what should/could go in your view file and what should/could go in your layout file.

Try this in your template:

```
title: "My Rad Page"
author: "My Rad Self"
---META

%h1= title
```

Let me know if you have any problems with this approach. 

I've been meaning to rewrite the readme and work on a getting started guide... hopefully I can get to that soon.

**Comment by bitfyre** [comment]
That did the trick. 

Thanks.
