### ISSUE TITLE
Option --version fails

### ISSUE THREAD

**Issue by Dahie** [trvsdnn/frank#75]
Executing 

```
$ frank --version
```

breaks and gives this stacktrace:

```
/Library/Ruby/Gems/1.8/gems/frank-1.0.10/bin/../lib/frank/cli.rb:72:in `set_options': uninitialized constant Frank::VERSION (NameError)
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1267:in `call'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1267:in `parse_in_order'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1254:in `catch'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1254:in `parse_in_order'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1248:in `order!'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1339:in `permute!'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1360:in `parse!'
from /Library/Ruby/Gems/1.8/gems/frank-1.0.10/bin/../lib/frank/cli.rb:82:in `set_options'
from /Library/Ruby/Gems/1.8/gems/frank-1.0.10/bin/../lib/frank/cli.rb:89:in `run'
from /Library/Ruby/Gems/1.8/gems/frank-1.0.10/bin/frank:20
from /usr/bin/frank:19:in `load'
from /usr/bin/frank:19
```

**Comment by trvsdnn** [comment]
Oops... Should be fixed in 1.0.11.
